name: nextstep-ai
region: nyc
services:
  - name: web
    github:
      repo: your-username/nextstep-ai
      branch: main
      deploy_on_push: true
    build_command: npm ci && npm run build
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3000
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: GEMINI_MODEL
        value: gemini-2.5-flash
      - key: ELEVENLABS_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: ELEVENLABS_VOICE_ID
        value: 21m00Tcm4TlvDq8ikWAM
      - key: MONGODB_URI
        scope: RUN_TIME
        type: SECRET
      - key: MONGODB_DB
        value: nextstep_ai
